//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQToolkitCodeGenSchema.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQToolkitCodeGenSchema.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;Long NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;LongText NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; PropertyName=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessSchema {
            get {
                return ResourceManager.GetString("AccessSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;Long NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;LongText NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; PropertyName=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessSchemaExcludeViews {
            get {
                return ResourceManager.GetString("AccessSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;Long NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;LongText NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; PropertyName= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessSchemaNoPluralization {
            get {
                return ResourceManager.GetString("AccessSchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;INT NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;VARCHAR(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; Pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MySqlSchema {
            get {
                return ResourceManager.GetString("MySqlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MySqlSchemaExcludeViews {
            get {
                return ResourceManager.GetString("MySqlSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;INT NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;VARCHAR(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MySqlSchemaNoPluralization {
            get {
                return ResourceManager.GetString("MySqlSchemaNoPluralization", resourceCulture);
            }
        }
        
        internal static byte[] Northwind35Sdf {
            get {
                object obj = ResourceManager.GetObject("Northwind35Sdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Northwind40Sdf {
            get {
                object obj = ResourceManager.GetObject("Northwind40Sdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindMdb {
            get {
                object obj = ResourceManager.GetObject("NorthwindMdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindSl3 {
            get {
                object obj = ResourceManager.GetObject("NorthwindSl3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindVfp {
            get {
                object obj = ResourceManager.GetObject("NorthwindVfp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleODPSchema {
            get {
                return ResourceManager.GetString("OracleODPSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleODPSchemaExcludeViews {
            get {
                return ResourceManager.GetString("OracleODPSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleODPSchemaNoPluralization {
            get {
                return ResourceManager.GetString("OracleODPSchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleSchema {
            get {
                return ResourceManager.GetString("OracleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleSchemaExcludeViews {
            get {
                return ResourceManager.GetString("OracleSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;CATEGORIES&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYID&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Decimal&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;NUMBER (*,0) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;22&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CATEGORYNAME&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;NVARCHAR2(30) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;30&quot; /&gt;
        ///    &lt;Column ColumnName=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleSchemaNoPluralization {
            get {
                return ResourceManager.GetString("OracleSchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;Category ID&quot; PropertyName=&quot;Category_ID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Category Name&quot; PropertyName=&quot;Category_Name&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nvarchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCe35Schema {
            get {
                return ResourceManager.GetString("SqlCe35Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SqlCe35SchemaExcludeViews {
            get {
                return ResourceManager.GetString("SqlCe35SchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;Category ID&quot; PropertyName=&quot;Category_ID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Category Name&quot; PropertyName=&quot;Category_Name&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nvarchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; Proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCe35SchemaNoPluralization {
            get {
                return ResourceManager.GetString("SqlCe35SchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;Category ID&quot; PropertyName=&quot;Category_ID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Category Name&quot; PropertyName=&quot;Category_Name&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nvarchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCe40Schema {
            get {
                return ResourceManager.GetString("SqlCe40Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SqlCe40SchemaExcludeViews {
            get {
                return ResourceManager.GetString("SqlCe40SchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;Category ID&quot; PropertyName=&quot;Category_ID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Category Name&quot; PropertyName=&quot;Category_Name&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nvarchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;Description&quot; Proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCe40SchemaNoPluralization {
            get {
                return ResourceManager.GetString("SqlCe40SchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;4&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;varchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLiteSchema {
            get {
                return ResourceManager.GetString("SQLiteSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;4&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;varchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLiteSchemaExcludeViews {
            get {
                return ResourceManager.GetString("SQLiteSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;CategoryID&quot; PropertyName=&quot;CategoryID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;false&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;4&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;varchar(15) NOT NULL&quot; Nullable=&quot;false&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLiteSchemaNoPluralization {
            get {
                return ResourceManager.GetString("SQLiteSchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Orders&quot; IsView=&quot;false&quot; EntityName=&quot;Order&quot;&gt;
        ///    &lt;Column ColumnName=&quot;OrderID&quot; PropertyName=&quot;OrderID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CustomerID&quot; PropertyName=&quot;CustomerID&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nchar(5)&quot; Nullable=&quot;true&quot; MaxLength=&quot;5&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;EmployeeID&quot; PropertyName=&quot;EmployeeID&quot; PropertyT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlServerSchema {
            get {
                return ResourceManager.GetString("SqlServerSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Orders&quot; IsView=&quot;false&quot; EntityName=&quot;Order&quot;&gt;
        ///    &lt;Column ColumnName=&quot;OrderID&quot; PropertyName=&quot;OrderID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CustomerID&quot; PropertyName=&quot;CustomerID&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nchar(5)&quot; Nullable=&quot;true&quot; MaxLength=&quot;5&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;EmployeeID&quot; PropertyName=&quot;EmployeeID&quot; PropertyT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlServerSchemaExcludeViews {
            get {
                return ResourceManager.GetString("SqlServerSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Orders&quot; IsView=&quot;false&quot; EntityName=&quot;Orders&quot;&gt;
        ///    &lt;Column ColumnName=&quot;OrderID&quot; PropertyName=&quot;OrderID&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;int NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;10&quot; Scale=&quot;0&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;CustomerID&quot; PropertyName=&quot;CustomerID&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;nchar(5)&quot; Nullable=&quot;true&quot; MaxLength=&quot;5&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;EmployeeID&quot; PropertyName=&quot;EmployeeID&quot; Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlServerSchemaNoPluralization {
            get {
                return ResourceManager.GetString("SqlServerSchemaNoPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;categoryid&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;I AUTOINC NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;4&quot; DefaultValue=&quot;&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;categoryname&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;C(15)&quot; Nullable=&quot;true&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;description&quot; Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VfpSchema {
            get {
                return ResourceManager.GetString("VfpSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Category&quot;&gt;
        ///    &lt;Column ColumnName=&quot;categoryid&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;I AUTOINC NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;4&quot; DefaultValue=&quot;&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;categoryname&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;C(15)&quot; Nullable=&quot;true&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;description&quot; Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VfpSchemaExcludeViews {
            get {
                return ResourceManager.GetString("VfpSchemaExcludeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema&gt;
        ///  &lt;Table TableName=&quot;Categories&quot; IsView=&quot;false&quot; EntityName=&quot;Categories&quot;&gt;
        ///    &lt;Column ColumnName=&quot;categoryid&quot; PropertyName=&quot;Categoryid&quot; PropertyType=&quot;System.Int32&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; DbType=&quot;I AUTOINC NOT NULL&quot; Nullable=&quot;false&quot; Precision=&quot;4&quot; DefaultValue=&quot;&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;categoryname&quot; PropertyName=&quot;Categoryname&quot; PropertyType=&quot;System.String&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; DbType=&quot;C(15)&quot; Nullable=&quot;true&quot; MaxLength=&quot;15&quot; /&gt;
        ///    &lt;Column ColumnName=&quot;description&quot; Proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VfpSchemaNoPluralization {
            get {
                return ResourceManager.GetString("VfpSchemaNoPluralization", resourceCulture);
            }
        }
    }
}
