//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQToolkitCodeGen.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQToolkitCodeGen.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;CodeGenSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Tables&gt;
        ///    &lt;Table TableName=&quot;Categories&quot; EntityName=&quot;Category&quot; Selected=&quot;true&quot;&gt;
        ///      &lt;Columns&gt;
        ///        &lt;Column ColumnName=&quot;CategoryId&quot; PropertyName=&quot;Id&quot; PropertyType=&quot;int&quot; Selected=&quot;true&quot; PrimaryKey=&quot;true&quot; Generated=&quot;true&quot; MaxLength=&quot;-1&quot; /&gt;
        ///        &lt;Column ColumnName=&quot;CategoryName&quot; PropertyName=&quot;CategoryName&quot; PropertyType=&quot;string&quot; Selected=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeGenSettingsSerializeTestXml {
            get {
                return ResourceManager.GetString("CodeGenSettingsSerializeTestXml", resourceCulture);
            }
        }
        
        internal static byte[] NorthwindMdb {
            get {
                object obj = ResourceManager.GetObject("NorthwindMdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindSdf {
            get {
                object obj = ResourceManager.GetObject("NorthwindSdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindSl3 {
            get {
                object obj = ResourceManager.GetObject("NorthwindSl3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NorthwindVfp {
            get {
                object obj = ResourceManager.GetObject("NorthwindVfp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfTable xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table TableName=&quot;alphabetical_list_of_products&quot; EntityName=&quot;alphabetical_list_of_products&quot; Selected=&quot;true&quot;&gt;
        ///    &lt;Columns&gt;
        ///      &lt;Column ColumnName=&quot;categoryid&quot; PropertyName=&quot;categoryid&quot; PropertyType=&quot;Int32&quot; Selected=&quot;false&quot; PrimaryKey=&quot;false&quot; Generated=&quot;false&quot; MaxLength=&quot;-1&quot; /&gt;
        ///      &lt;Column ColumnName=&quot;categoryname&quot; PropertyName=&quot;categoryname&quot; Pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VfpGetTables {
            get {
                return ResourceManager.GetString("VfpGetTables", resourceCulture);
            }
        }
    }
}
